### ISSUE TITLE
List of events - links to all the titles

### ISSUE THREAD

**Issue by faithful-dove** [cosmic-brook/mgt656-spring-2015-project#1]

**Comment by judywschang** [comment]
Title: clickable link that will provide more information regarding to the event
content for the event
Date: year, month, date
Location: address
Time: hours, minutes
Availabilities: how many available tickets are left
Capacity: how many people this event would hold

**Comment by judywschang** [comment]
https://www.youtube.com/watch?v=vNc-1GXKH34&index=3&list=PLEsf0fWhK8Xmi20t1VARjefbwAI5abiDQ

**Comment by judywschang** [comment]
Completed and test passed - pending merging!

**Comment by judywschang** [comment]
Merge complete

**Comment by judywschang** [comment]
New Issue: somehow the changes have disappeared, so need to add in the links again
