### ISSUE TITLE
Expired events

### ISSUE THREAD

**Issue by faithful-dove** [cosmic-brook/mgt656-spring-2015-project#2]

**Comment by nlovejoy** [comment]
There is a video - make sure to pass test below

✓ should not show events that are over

**Comment by judywschang** [comment]
https://www.youtube.com/watch?v=1QkK52kdKWg&list=PLEsf0fWhK8Xmi20t1VARjefbwAI5abiDQ&index=4

**Comment by judywschang** [comment]
Done! Test passed! Waiting for merging
