### ISSUE TITLE
Create new event

### ISSUE THREAD

**Issue by faithful-dove** [cosmic-brook/mgt656-spring-2015-project#4]
Add event creation form with required fields - there is a video for this...

**Comment by nlovejoy** [comment]
See below for requirements - the two checked items currently pass

The form for creating new events
     12) should display errors to the user when the year is not an integer
     13) should display errors to the user when the year is more than 2016
     14) should display errors to the user when the year is less than 2015
     15) should display errors to the user when the month is not an integer
     16) should display errors to the user when the month is more than 11
     17) should display errors to the user when the month is less than 0
     18) should display errors to the user when the day is not an integer
     19) should display errors to the user when the day is more than 31
     20) should display errors to the user when the day is less than 1
     21) should display errors to the user when the hour is not an integer
     22) should display errors to the user when the hour is more than 23
     23) should display errors to the user when the hour is less than 0
     24) should display errors to the user when the image is not a gif or png
     25) should display errors to the user when the image is not a URL
     26) should display errors to the user when the location is too long
     27) should display errors to the user when the location is empty
     ✓ should display errors to the user when the title is too long
     ✓ should display errors to the user when the title is empty
     28) should redirect the user to the event detail page if the form is valid

**Comment by judywschang** [comment]
Same as 21
